version: '3.8'
services:
  xfblog:
    build: ../
    image: testboot
    depends_on:
      - redis
      - mysql
    ports:
      - "8888:8080"


  redis:
    image: "redis:3.2"
    container_name: app_redis
    ports:
      - 6378:6379

  mysql:
    image: "mysql"
    container_name: app_mysql
    restart: always
    volumes:
      - ../sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xfblog
    ports:
      - 3305:3306
