spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/XFBlog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#配置日志
logging:
  level:
    #不同目录下的日志可配置不同级别
    root: info
    com.star: debug
    #采用相对路径方式将日志文件输出到【log/blog-dev.log】
  file: 
    name: log/blog-dev.log

#起别名，mapper路径，驼峰命名规则
mybatis:
  type-aliases-package: com.ldf.demo.pojo
  mapper-locations: classpath:com.ldf.demo.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#配置端口
server:
  port: 8080

shiro:
  retry: 5 # 重试次数
  lock: 5 # 锁定次数
  lock-duration: 1 # 锁定时长 min
  disabled: false # A&A开关
  session:
    timeout: 1800000
  loginurl: /admin
  jwt:
    maxAliveMinute: 1 # jwt token过期时间,单位minutes
  maxIdleMinute: 120 # Jwt token最大存活时间，单位minutes
